#2: Add project skeleton
itsallcode/openfasttrace-asciidoc-plugin pull request #3
Opened 2024-07-20 10:29 UTC by redcatbear

Closes #2.

This PR add skeleton directories and files for the mandatory documenation of OFT sub-projects.

2024-07-20 12:44 UTC, kaklakariada requested changes

2024-07-20 12:44 UTC, kaklakariada commented on doc/developer_guide.md
> +By default, the AsciiDoc plugin is built with Java 11. To build and test with a later version of Java, add argument `-Djava.version=17` to the Maven command.
```suggestion
By default, the AsciiDoc plugin is built with Java 17. To build and test with a later version of Java, add argument `-Djava.version=21` to the Maven command.
```

2024-07-20 12:44 UTC, kaklakariada commented on doc/developer_guide.md
> +mvn -Djava.version=17 package -DskipTests
```suggestion
mvn -Djava.version=21 package -DskipTests
```

2024-07-20 12:44 UTC, kaklakariada commented on doc/spec/system_requirement.md
Should be in asciidoc format to demonstrate the importer.

2024-07-20 12:44 UTC, kaklakariada commented on doc/spec/design.md
Should be in asciidoc format to demonstrate the importer.

2024-07-20 13:56 UTC, kaklakariada submitted a review, later dismissed

2024-07-23 07:51 UTC, sophokles73 commented
@redcatbear seems like there are some broken links that need to be fixed in order for this to get merged?

2024-07-23 08:38 UTC, kaklakariada commented
@sophokles73 The broken links are expected, they should be fixed after we published the first release to maven central. This PR is just waiting for a final review by @redcatbear , because I also added some changes.

You can already start development based on `main` or this branch, there should not be too many merge conflicts.

2024-07-23 09:42 UTC, redcatbear reviewed
I can only comment (not approve), since I am the original author. @kaklakariada, your changes look good to me. Broken links expected, as you already pointed out. Until the first Maven release.

2024-07-23 10:35 UTC, kaklakariada approved these changes

2024-07-23 10:35 UTC, merged

2024-07-23 10:37 UTC, kaklakariada commented
I excluded the link check from required pr checks for now, so it won't block merging.